name: Code coverage

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: '--deny warnings'
  MINIMUM_SUPPORTED_RUST_VERSION: 1.85.0
  RUST_CHANNEL: stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup component add --toolchain ${{ env.RUST_CHANNEL }} rustfmt rust-src clippy
          rustup default ${{ env.RUST_CHANNEL }}
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32
      - name: Install cargo-tarpaulin
        run: cargo install --locked cargo-tarpaulin
      - name: Run cargo tarpaulin
        run: cargo tarpaulin --all-features --out Xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
