name: Developer Experience

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: '--deny warnings'
  MINIMUM_SUPPORTED_RUST_VERSION: 1.85.0
  GOLANG_VERSION: 1.23.3
  JS_VERSION: 22
  RUST_CHANNEL: stable

on:
  schedule:
    - cron: "0 0 1 * *"
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  try-it:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Setup JBang
        uses: jbangdev/setup-jbang@312c53a4221283f9c8e4aa84d8261b82f0c680fb
      - name: Setup JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run try-it.sh
        run: bash docs/try-it.sh
        env:
          YOZEFU_API_URL: http://localhost:8081/schemas/types

  wasm-rust:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - run: |
          rustup update --no-self-update ${RUST_CHANNEL}
          rustup default ${RUST_CHANNEL}
        env:
          RUST_CHANNEL: ${{ env.RUST_CHANNEL }}
      - name: Setup Go ${{ env.GOLANG_VERSION }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Install extism CLI
        run: go install github.com/extism/cli/extism@latest
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32
      - name: Temporary fix in Cargo.toml
        run: sed -i -E 's#git = "ssh.+#path = "../../wasm-types" }#g' crates/wasm-blueprints/rust/Cargo.toml
      - name: Build a Rust search filter
        run: make -C crates/wasm-blueprints/rust/ build test

  wasm-golang:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Setup Go ${{ env.GOLANG_VERSION }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Install extism CLI
        run: go install github.com/extism/cli/extism@latest
      - uses: acifani/setup-tinygo@db56321a62b9a67922bb9ac8f9d085e218807bb3
        with:
          tinygo-version: '0.34.0'
      - name: Build a Golang search filter
        run: make -C crates/wasm-blueprints/golang/ build test

  wasm-js:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Setup JS ${{ env.JS_VERSION }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ env.JS_VERSION }}
      - name: Setup Go ${{ env.GOLANG_VERSION }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Install extism CLI
        run: go install github.com/extism/cli/extism@latest
      - name: Build a JS search filter
        run: make -C crates/wasm-blueprints/js/ build test
        continue-on-error: true


  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    continue-on-error: true
    strategy:
      matrix:
        package:
          - name: rust
            directory: ./crates/wasm-blueprints/rust/
          - name: golang
            directory: ./crates/wasm-blueprints/golang/
          - name: js
            directory: ./crates/wasm-blueprints/js/
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Run docker build
        run: docker build ${{ matrix.package.directory }}
