name: Publish

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: '--deny warnings'
  MINIMUM_SUPPORTED_RUST_VERSION: 1.85.0
  DOCKER_REGISTRY: ghcr.io
  RUST_CHANNEL: stable


on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    
  workflow_call:
#  workflow_run:
#    workflows: ['Tag']
#    types:
#      - completed

jobs:
  version:
    name: Determine version to publish
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Install Rust
        run: |
          rustup update --no-self-update ${RUST_CHANNEL}
          rustup component add --toolchain ${RUST_CHANNEL} cargo
          rustup default ${RUST_CHANNEL}
        env:
          RUST_CHANNEL: ${{ env.RUST_CHANNEL }}
      - id: release
        run: echo "version=$(cargo pkgid --manifest-path crates/bin/Cargo.toml | cut -d '@' -f2)" >> "$GITHUB_OUTPUT"

  create-release:
    runs-on: ubuntu-latest
    name: Create release
    needs: version
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Create github release
        run: gh release create "v${VERSION}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.version.outputs.version }}

  changelog:
    needs: [version, create-release]
    uses: ./.github/workflows/changelog.yml
    name: Create changelog
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

  build-and-publish:
    needs: [version, create-release]
    name: Build and publish
    runs-on: ${{ matrix.platforms.os }}
    permissions:
      contents: write
      attestations: write
      id-token: write
      artifact-metadata: write
    strategy:
      matrix:
        platforms:
          - os: macos-15
            target: aarch64-apple-darwin
            features: "--features gssapi-vendored,libz-static,ssl-vendored"
          - os: macos-15-intel
            target: x86_64-apple-darwin
            features: "--features gssapi-vendored,libz-static,ssl-vendored"
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            features: "--features gssapi-vendored,libz-static,ssl-vendored"
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            features: "--features gssapi-vendored,libz-static,ssl-vendored"
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            features: "--no-default-features"
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            features: "--no-default-features --features ssl-vendored"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
        if: matrix.platforms.os == 'ubuntu-latest' || matrix.platforms.os == 'ubuntu-24.04-arm'
      - uses: houseabsolute/actions-rust-cross@576730dbfbb705690d43bd285987a3094fd84874
        with:
          target: ${{ matrix.platforms.target }}
          args: "--verbose --locked --release ${{ matrix.platforms.features }}"
          strip: true

      - name: Setup variables
        id: variables
        shell: bash
        run: |
          name="$(cargo metadata --manifest-path crates/bin/Cargo.toml --no-deps --format-version=1 | jq -r '.packages[] | select(.name=="yozefu").targets[0].name')"
          source=target/${{ matrix.platforms.target }}/release/${name}
          archive="yozefu-${{matrix.platforms.target }}"
          subjectName="${name}-${{matrix.platforms.target }}-${VERSION}"
          binaryName="${subjectName}"
          destination="dist/${binaryName}"
          if [ "${{ matrix.platforms.os }}" = "windows-latest" ]; then
             source=${source}.exe
             binaryName=${binaryName}.exe
             destination="dist/${binaryName}"
          fi
          {
            echo "name=${name}"
            echo "source=${source}"
            echo "archive=${archive}"
            echo "sbom=dist/${archive}.cdx.json"
            echo "subjectName=${subjectName}"
            echo "destination=${destination}"
            echo "binaryName=${binaryName}"
          } >> "$GITHUB_OUTPUT"
        env:
          VERSION: ${{ needs.version.outputs.version }}


      - name: cargo install cargo-cyclonedx
        run: cargo install --locked cargo-cyclonedx
      
      - name: Generate SBOM
        run: cargo cyclonedx --describe binaries --format json ${{ matrix.platforms.features }} --target ${{ matrix.platforms.target }}
      
      - name: Rename SBOM
        shell: bash
        run: mv crates/bin/${NAME}_bin.cdx.json "${SBOM}"
        env:
          SBOM: ${{ steps.variables.outputs.sbom }}
          ARCHIVE: ${{ steps.variables.outputs.archive }}
          NAME: ${{ steps.variables.outputs.name }}

      - name: Upload binary
        shell: bash
        run: gh release upload "v${VERSION}" dist/* --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.version.outputs.version }}
          # https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

      - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26
        with:
          subject-path: "${{ steps.variables.outputs.source }}"
          sbom-path: "${{ steps.variables.outputs.sbom }}"
          subject-name: "${{ steps.variables.outputs.archive }}-${{ needs.version.outputs.version }}"

      - name: Attest build provenance
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a
        with:
          subject-path: "${{ steps.variables.outputs.source }}"
          sbom-path: "${{ steps.variables.outputs.sbom }}"
          subject-name: "${{ steps.variables.outputs.archive }}-${{ needs.version.outputs.version }}"
        env:
          VERSION: ${{ needs.version.outputs.version }}
          SOURCE: ${{ steps.variables.outputs.source }}
          ARCHIVE: ${{ steps.variables.outputs.archive }}

      - name: Create temp dir
        run: mkdir -p dist

      - name: Rename binary
        shell: bash
        run: mv "${SOURCE}" "${DEST}"
        env:
          SOURCE: ${{ steps.variables.outputs.source }}
          DEST: ${{ steps.variables.outputs.destination }}

      - name: Build archive for Windows
        shell: bash
        working-directory: ./dist
        if: matrix.platforms.os == 'windows-latest'
        run: 7z a "${ARCHIVE}.zip" "${BINARY}"
        env:
          ARCHIVE: ${{ steps.variables.outputs.archive }}
          BINARY: ${{ steps.variables.outputs.binaryName }}

      - name: Build archive for unix systems
        if: matrix.platforms.os != 'windows-latest'
        shell: bash
        working-directory: ./dist
        run: "tar cvzf \"${ARCHIVE}.tar.gz\" \"${BINARY}\" \n"
        env:
          ARCHIVE: ${{ steps.variables.outputs.archive }}
          BINARY: ${{ steps.variables.outputs.binaryName }}
      - name: Clean release directory
        shell: bash
        run: rm -f "dist/${BINARY}"
        env:
          BINARY: ${{ steps.variables.outputs.binaryName }}


  publish-docker-image:
    name: Docker image
    runs-on: ubuntu-latest
    needs: [version, create-release]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ needs.version.outputs.version }}
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          labels: |
            org.opencontainers.image.description=Yozefu is a CLI tool for Apache kafka. It allows you to navigate topics and search Kafka records.
            org.opencontainers.image.vendor=Yann Prono
            org.opencontainers.image.licenses=Apache-2.0
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        id: push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          sbom: true
          annotations: ${{ steps.meta.outputs.annotations }}
      # https://github.com/actions/attest-build-provenance
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a
        with:
          subject-name: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  
  publish-to-registry:
    runs-on: ubuntu-latest
    name: Publish to registry
    needs: [version, build-and-publish]
    if: github.ref == 'refs/heads/main'
    environment: production
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      # https://crates.io/docs/trusted-publishing
      - name: Install Rust
        run: |
          rustup update --no-self-update ${RUST_CHANNEL}
          rustup component add --toolchain ${RUST_CHANNEL} cargo
          rustup default ${RUST_CHANNEL}
        env:
          RUST_CHANNEL: ${{ env.RUST_CHANNEL }}
      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec
        id: auth
      - run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
      - run: cargo publish --workspace
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
