name: Security

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: '--deny warnings'
  MINIMUM_SUPPORTED_RUST_VERSION: 1.85.0

on:
  schedule:
    - cron: "0 10 * * MON" # every monday, at 10AM
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  dependencies:
   runs-on: ubuntu-latest
   if: ${{ github.actor != 'dependabot[bot]' }}
   permissions:
      contents: read
   steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install cargo-edit
        run: cargo install --locked cargo-edit
      - name: Check for outdated dependencies
        run: cargo upgrade --dry-run --locked

  audit:
   runs-on: ubuntu-latest
   permissions:
    contents: read
   steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install cargo-outdated
        run: cargo install --locked cargo-audit
      - name: Cargo audit
        run: cargo audit